{% set name = "lavue" %}
{% set version = "2.93.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lavue-{{ version }}.tar.gz
  sha256: 9f69ff9003ed7d1c003785035517096007799c6d26d7cf1b7243d3b1976f054d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - h5py
    - numpy >1.6.0
    - pyqt
    - pyqtgraph >=0.10.0
    - python >={{ python_min }}
    - pytz
    - pyzmq
    - requests
    - scipy

test:
  imports:
    - lavuelib
    - lavuelib.plugins
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - lavue --help
    - lavuemonitor --help


about:
  home: https://github.com/lavue-org/lavue
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Live image viewer application for photon science detectors.
  description: |
    This is a simple implementation of a live viewer front end.
    It is supposed to show a live image view from xray-detectors
    at PETRA3 @ desy.de, e.g. Pilatus, Lambda, Eiger, PerkinElmer,
    PCO, LimaCCD, and others.
  dev_url: https://github.com/lavue-org/lavue
  doc_url: https://confluence.desy.de/display/FSEC/LaVue+-+Live+Image+Viewer

extra:
  recipe-maintainers:
    - beenje
